name: UpdateTODO

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/30 * * * *' 
    
on: push #Used for Debug

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Run a one-line script
      run: python ./.github/workflows/todo_List.py
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: push code to master
      run: git push origin master
    - name: username
      run: logankilpatrick 
    - name: password
      run: ${{ secrets.password }}        
      
